version: "3.9"

services:
  java_app:
    container_name: ${APP_HOST:-java_app}
    image: pee-java_app:1.0.0
    build: .
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    env_file:
      - ./.env
    depends_on:
      - java_db
    networks:
      - public
  java_db:
    container_name: ${POSTGRES_HOST:-postgres_db}
    image: postgres:12
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    env_file:
      - ./.env

networks:
  public:
    external: true