services:
  # RabbitMQ Message Broker Service
  rabbitmq_broker:
    container_name: rabbitmq_broker # Uses RABBITMQ_HOST from .env, defaults to 'rabbitmq_broker'
    image: rabbitmq:3-management # Includes the RabbitMQ management UI
    ports:
      - "${RABBITMQ_PORT:-5672}:${RABBITMQ_PORT:-5672}" # Maps host port to container port for RabbitMQ client connections
      - "15672:15672" # Maps host port to container port for RabbitMQ Management UI
    env_file:
      - ./.env # Loads environment variables for RabbitMQ from the .env file
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # MongoDB Database Service
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  mongo_data:
